name: quicktype_dart_example
description: Runtime + build_runner usage of quicktype_dart.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  quicktype_dart:
    path: ../

dev_dependencies:
  build_runner: ^2.4.15
  lints: ^5.0.0
