#!/usr/bin/env python3
"""Generate a C file embedding JS prelude + bundle as byte arrays.

Usage:
  embed_bundle.py <prelude.js> <bundle.js> <out.c>

Output defines:
  const unsigned char qt_prelude_js[]        — prelude bytes
  const unsigned long qt_prelude_js_len      — prelude length
  const unsigned char qt_bundle_js[]         — bundle bytes
  const unsigned long qt_bundle_js_len       — bundle length
"""
import sys


def emit(path, symbol, out):
    with open(path, "rb") as f:
        data = f.read()
    out.write(f"const unsigned char {symbol}[] = {{\n")
    for i in range(0, len(data), 20):
        chunk = data[i:i + 20]
        out.write("  " + ",".join(f"0x{b:02x}" for b in chunk) + ",\n")
    out.write("};\n")
    out.write(f"const unsigned long {symbol}_len = {len(data)};\n\n")


def main():
    if len(sys.argv) != 4:
        print(__doc__, file=sys.stderr)
        sys.exit(1)
    prelude, bundle, out_path = sys.argv[1:]
    with open(out_path, "w", encoding="utf-8") as out:
        out.write("// Auto-generated by embed_bundle.py — do not edit.\n\n")
        emit(prelude, "qt_prelude_js", out)
        emit(bundle, "qt_bundle_js", out)


if __name__ == "__main__":
    main()
