#!/usr/bin/env python3
"""Generate a C file embedding JS prelude + bundle as byte arrays.

Emits printable ASCII bytes as-is (inside a C string literal) and escapes
everything else. Chunks into ≤4KB segments so adjacent string literals can
be concatenated by the C compiler without hitting its per-literal size limit.

Usage:
  embed_bundle.py <prelude.js> <bundle.js> <out.c>

Output defines:
  const unsigned char qt_prelude_js[]        — prelude bytes + trailing NUL
  const unsigned long qt_prelude_js_len      — prelude length (bytes, no NUL)
  const unsigned char qt_bundle_js[]         — bundle bytes + trailing NUL
  const unsigned long qt_bundle_js_len       — bundle length
"""
import sys

# Characters that must not appear raw inside a C string literal.
_ESCAPE = {
    0x22: b'\\"',       # "
    0x5C: b'\\\\',      # \
    0x0A: b'\\n',       # newline
    0x0D: b'\\r',       # CR
    0x09: b'\\t',       # tab
    0x00: b'\\0',       # nul
    # '?' is escaped as \? to avoid accidental trigraph formation on old
    # compilers — modern clang/gcc don't care but it's cheap insurance.
    0x3F: b'\\?',
}


def escape(data):
    out = bytearray()
    for b in data:
        esc = _ESCAPE.get(b)
        if esc is not None:
            out += esc
        elif 32 <= b <= 126:
            out.append(b)
        else:
            out += f'\\x{b:02x}'.encode('ascii')
    return bytes(out)


def emit(path, symbol, out):
    try:
        with open(path, 'rb') as f:
            data = f.read()
    except FileNotFoundError:
        print(
            f'embed_bundle.py: input file not found: {path}\n'
            f'Did you run build_bundle.sh first?',
            file=sys.stderr,
        )
        sys.exit(2)
    except OSError as e:
        print(f'embed_bundle.py: cannot read {path}: {e}', file=sys.stderr)
        sys.exit(2)
    out.write(f'const unsigned char {symbol}[] = \n'.encode('ascii'))
    # Chunk into 4KB source-bytes to avoid compiler string-literal limits.
    chunk_size = 4096
    for start in range(0, len(data), chunk_size):
        chunk = data[start:start + chunk_size]
        out.write(b'  "')
        out.write(escape(chunk))
        out.write(b'"\n')
    out.write(b';\n')
    out.write(f'const unsigned long {symbol}_len = {len(data)};\n\n'.encode('ascii'))


def main():
    if len(sys.argv) != 4:
        print(__doc__, file=sys.stderr)
        sys.exit(1)
    prelude, bundle, out_path = sys.argv[1:]
    try:
        out = open(out_path, 'wb')
    except OSError as e:
        print(
            f'embed_bundle.py: cannot open output {out_path} for writing: {e}',
            file=sys.stderr,
        )
        sys.exit(2)
    with out:
        out.write(b'// Auto-generated by embed_bundle.py \xe2\x80\x94 do not edit.\n\n')
        emit(prelude, 'qt_prelude_js', out)
        emit(bundle, 'qt_bundle_js', out)


if __name__ == '__main__':
    main()
