// Generated by tool/gen_options.py from `lang_ruby.dart`.
// Do not edit by hand — regenerate when the underlying *Args class changes.

import '../args.dart';
import '../renderer_options.dart';

/// Named-parameter options for the Ruby target.
///
/// Pass to [QuicktypeDart.generate] via `options:`. Mirrors the flags
/// on the older [RubyArgs] class
/// (which is retained but deprecated — see migration notes in v0.3.0).
class RubyRendererOptions extends RendererOptions {
  const RubyRendererOptions({
    this.justTypes,
    this.strictness,
    this.namespace,
  });

  final bool? justTypes;
  final RubyStrictness? strictness;
  final String? namespace;

  @override
  Map<String, String> toRendererOptions() {
    final m = <String, String>{};
    if (justTypes != null) m['just-types'] = justTypes.toString();
    if (strictness != null) m['strictness'] = strictness!.toString();
    if (namespace != null) m['namespace'] = namespace!;
    return m;
  }
}
