// Generated by tool/gen_options.py from `lang_haskell.dart`.
// Do not edit by hand — regenerate when the underlying *Args class changes.

import '../args.dart';
import '../renderer_options.dart';

/// Named-parameter options for the Haskell target.
///
/// Pass to [QuicktypeDart.generate] via `options:`. Mirrors the flags
/// on the older [HaskellArgs] class
/// (which is retained but deprecated — see migration notes in v0.3.0).
class HaskellRendererOptions extends RendererOptions {
  const HaskellRendererOptions({
    this.justTypes,
    this.module,
    this.arrayType,
  });

  final bool? justTypes;
  final String? module;
  final ArrayType? arrayType;

  @override
  Map<String, String> toRendererOptions() {
    final m = <String, String>{};
    if (justTypes != null) m['just-types'] = justTypes.toString();
    if (module != null) m['module'] = module!;
    if (arrayType != null) m['array-type'] = arrayType!.toString();
    return m;
  }
}
