// Generated by tool/gen_options.py from `lang_python.dart`.
// Do not edit by hand — regenerate when the underlying *Args class changes.

import '../args.dart';
import '../renderer_options.dart';

/// Named-parameter options for the Python target.
///
/// Pass to [QuicktypeDart.generate] via `options:`. Mirrors the flags
/// on the older [PythonArgs] class
/// (which is retained but deprecated — see migration notes in v0.3.0).
class PythonRendererOptions extends RendererOptions {
  const PythonRendererOptions({
    this.pythonVersion,
    this.justTypes,
    this.nicePropertyNames,
    this.pydanticBaseModel,
  });

  final PythonVersion? pythonVersion;
  final bool? justTypes;
  final bool? nicePropertyNames;
  final bool? pydanticBaseModel;

  @override
  Map<String, String> toRendererOptions() {
    final m = <String, String>{};
    if (pythonVersion != null) m['python-version'] = pythonVersion!.toString();
    if (justTypes != null) m['just-types'] = justTypes.toString();
    if (nicePropertyNames != null) m['nice-property-names'] = nicePropertyNames.toString();
    if (pydanticBaseModel != null) m['pydantic-base-model'] = pydanticBaseModel.toString();
    return m;
  }
}
