// Generated by tool/gen_options.py from `lang_proptypes.dart`.
// Do not edit by hand — regenerate when the underlying *Args class changes.

import '../args.dart';
import '../renderer_options.dart';

/// Named-parameter options for the PropTypes target.
///
/// Pass to [QuicktypeDart.generate] via `options:`. Mirrors the flags
/// on the older [PropTypesArgs] class
/// (which is retained but deprecated — see migration notes in v0.3.0).
class PropTypesRendererOptions extends RendererOptions {
  const PropTypesRendererOptions({
    this.acronymStyle,
    this.converters,
  });

  final AcronymStyle? acronymStyle;
  final ConverterType? converters;

  @override
  Map<String, String> toRendererOptions() {
    final m = <String, String>{};
    if (acronymStyle != null) m['acronym-style'] = acronymStyle!.toString();
    if (converters != null) m['converters'] = converters!.toString();
    return m;
  }
}
