// Generated by tool/gen_options.py from `lang_kotlin.dart`.
// Do not edit by hand — regenerate when the underlying *Args class changes.

import '../args.dart';
import '../renderer_options.dart';

/// Named-parameter options for the Kotlin target.
///
/// Pass to [QuicktypeDart.generate] via `options:`. Mirrors the flags
/// on the older [KotlinArgs] class
/// (which is retained but deprecated — see migration notes in v0.3.0).
class KotlinRendererOptions extends RendererOptions {
  const KotlinRendererOptions({
    this.framework,
    this.acronymStyle,
    this.package,
  });

  final KotlinFramework? framework;
  final AcronymStyle? acronymStyle;
  final String? package;

  @override
  Map<String, String> toRendererOptions() {
    final m = <String, String>{};
    if (framework != null) m['framework'] = framework!.toString();
    if (acronymStyle != null) m['acronym-style'] = acronymStyle!.toString();
    if (package != null) m['package'] = package!;
    return m;
  }
}
