// Generated by tool/gen_options.py from `lang_smithy.dart`.
// Do not edit by hand — regenerate when the underlying *Args class changes.

import '../args.dart';
import '../renderer_options.dart';

/// Named-parameter options for the Smithy target.
///
/// Pass to [QuicktypeDart.generate] via `options:`. Mirrors the flags
/// on the older [SmithyArgs] class
/// (which is retained but deprecated — see migration notes in v0.3.0).
class SmithyRendererOptions extends RendererOptions {
  const SmithyRendererOptions({
    this.framework,
    this.package,
  });

  final SmithyFramework? framework;
  final String? package;

  @override
  Map<String, String> toRendererOptions() {
    final m = <String, String>{};
    if (framework != null) m['framework'] = framework!.toString();
    if (package != null) m['package'] = package!;
    return m;
  }
}
