// Generated by tool/gen_options.py from `lang_c.dart`.
// Do not edit by hand — regenerate when the underlying *Args class changes.

import '../args.dart';
import '../renderer_options.dart';

/// Named-parameter options for the C target.
///
/// Pass to [QuicktypeDart.generate] via `options:`. Mirrors the flags
/// on the older [CArgs] class
/// (which is retained but deprecated — see migration notes in v0.3.0).
class CRendererOptions extends RendererOptions {
  const CRendererOptions({
    this.printStyle,
    this.hashtableSize,
    this.typedefAlias,
    this.sourceStyle,
    this.integerSize,
    this.typeStyle,
    this.memberStyle,
    this.enumeratorStyle,
  });

  final PrintStyle? printStyle;
  final String? hashtableSize;
  final TypedefAlias? typedefAlias;
  final SourceStyle? sourceStyle;
  final IntegerSize? integerSize;
  final NamingStyle? typeStyle;
  final NamingStyle? memberStyle;
  final NamingStyle? enumeratorStyle;

  @override
  Map<String, String> toRendererOptions() {
    final m = <String, String>{};
    if (printStyle != null) m['print-style'] = printStyle!.toString();
    if (hashtableSize != null) m['hashtable-size'] = hashtableSize!;
    if (typedefAlias != null) m['typedef-alias'] = typedefAlias!.toString();
    if (sourceStyle != null) m['source-style'] = sourceStyle!.toString();
    if (integerSize != null) m['integer-size'] = integerSize!.toString();
    if (typeStyle != null) m['type-style'] = typeStyle!.toString();
    if (memberStyle != null) m['member-style'] = memberStyle!.toString();
    if (enumeratorStyle != null) m['enumerator-style'] = enumeratorStyle!.toString();
    return m;
  }
}
