// Generated by tool/gen_options.py from `lang_dart.dart`.
// Do not edit by hand — regenerate when the underlying *Args class changes.

import '../args.dart';
import '../renderer_options.dart';

/// Named-parameter options for the Dart target.
///
/// Pass to [QuicktypeDart.generate] via `options:`. Mirrors the flags
/// on the older [DartArgs] class
/// (which is retained but deprecated — see migration notes in v0.3.0).
class DartRendererOptions extends RendererOptions {
  const DartRendererOptions({
    this.nullSafety,
    this.justTypes,
    this.codersInClass,
    this.fromMap,
    this.requiredProps,
    this.finalProps,
    this.copyWith,
    this.useFreezed,
    this.useHive,
    this.useJsonAnnotation,
    this.partName,
  });

  final bool? nullSafety;
  final bool? justTypes;
  final bool? codersInClass;
  final bool? fromMap;
  final bool? requiredProps;
  final bool? finalProps;
  final bool? copyWith;
  final bool? useFreezed;
  final bool? useHive;
  final bool? useJsonAnnotation;
  final String? partName;

  @override
  Map<String, String> toRendererOptions() {
    final m = <String, String>{};
    if (nullSafety != null) m['null-safety'] = nullSafety.toString();
    if (justTypes != null) m['just-types'] = justTypes.toString();
    if (codersInClass != null) m['coders-in-class'] = codersInClass.toString();
    if (fromMap != null) m['from-map'] = fromMap.toString();
    if (requiredProps != null) m['required-props'] = requiredProps.toString();
    if (finalProps != null) m['final-props'] = finalProps.toString();
    if (copyWith != null) m['copy-with'] = copyWith.toString();
    if (useFreezed != null) m['use-freezed'] = useFreezed.toString();
    if (useHive != null) m['use-hive'] = useHive.toString();
    if (useJsonAnnotation != null) m['use-json-annotation'] = useJsonAnnotation.toString();
    if (partName != null) m['part-name'] = partName!;
    return m;
  }
}
