#!/usr/bin/env python3
"""Generates DartRendererOptions-style classes from the existing
`lib/src/models/args/lang_*.dart` files. Writes to
`lib/src/models/options/lang_*.dart`."""

import os
import re
import sys

ROOT = '/Users/jake/Development/internal/quicktype_dart'
ARGS_DIR = os.path.join(ROOT, 'lib', 'src', 'models', 'args')
OPTS_DIR = os.path.join(ROOT, 'lib', 'src', 'models', 'options')

# Pattern that matches `static <ArgType> get <dartName> => <ArgType>('<cliName>');`
# across single or two lines. The `argtype` on the getter side sometimes omits
# the enum type parameter in the existing source (e.g. CArgs), so we allow
# EnumArg with or without it. The `ctor` always has the type parameter.
PATTERN = re.compile(
    r"static\s+(?P<argtype>BoolArg|StringArg|SimpleArg|EnumArg(?:<[A-Za-z0-9]+>)?|RepeatableArg)"
    r"\s+get\s+(?P<name>[a-zA-Z0-9_]+)\s*=>\s*"
    r"(?P<ctor>BoolArg|StringArg|SimpleArg|EnumArg<(?P<enum>[A-Za-z0-9]+)>|RepeatableArg)"
    r"\s*\(\s*'(?P<cli>[^']+)'\s*(?:,[^)]*)?\)\s*;",
    re.DOTALL,
)

# Language files and the Options-class name we'll emit.
FILES = [
    ('lang_c.dart', 'CRendererOptions'),
    ('lang_cpp.dart', 'CppRendererOptions'),
    ('lang_csharp.dart', 'CSharpRendererOptions'),
    ('lang_dart.dart', 'DartRendererOptions'),
    ('lang_elixir.dart', 'ElixirRendererOptions'),
    ('lang_elm.dart', 'ElmRendererOptions'),
    ('lang_flow.dart', 'FlowRendererOptions'),
    ('lang_go.dart', 'GoRendererOptions'),
    ('lang_haskell.dart', 'HaskellRendererOptions'),
    ('lang_java.dart', 'JavaRendererOptions'),
    ('lang_javascript.dart', 'JavaScriptRendererOptions'),
    ('lang_kotlin.dart', 'KotlinRendererOptions'),
    ('lang_objc.dart', 'ObjectiveCRendererOptions'),
    ('lang_php.dart', 'PHPRendererOptions'),
    ('lang_proptypes.dart', 'PropTypesRendererOptions'),
    ('lang_python.dart', 'PythonRendererOptions'),
    ('lang_ruby.dart', 'RubyRendererOptions'),
    ('lang_rust.dart', 'RustRendererOptions'),
    ('lang_scala.dart', 'Scala3RendererOptions'),
    ('lang_smithy.dart', 'SmithyRendererOptions'),
    ('lang_swift.dart', 'SwiftRendererOptions'),
    ('lang_typescript.dart', 'TypeScriptRendererOptions'),
]

os.makedirs(OPTS_DIR, exist_ok=True)
index_exports = []

for filename, classname in FILES:
    src_path = os.path.join(ARGS_DIR, filename)
    with open(src_path) as f:
        src = f.read()

    entries = []  # list of (dart_field_type, dart_field_name, cli_name, kind)
    for m in PATTERN.finditer(src):
        ctor = m.group('ctor')
        name = m.group('name')
        cli = m.group('cli')
        if ctor == 'BoolArg' or ctor == 'SimpleArg':
            field_type = 'bool?'
            kind = 'bool'
        elif ctor == 'StringArg':
            field_type = 'String?'
            kind = 'string'
        elif ctor == 'RepeatableArg':
            field_type = 'List<String>?'
            kind = 'list'
        elif ctor.startswith('EnumArg<'):
            enum_name = m.group('enum')
            field_type = f'{enum_name}?'
            kind = 'enum'
        else:
            continue
        entries.append((field_type, name, cli, kind))

    if not entries:
        print(f'  skip {filename} — no args parsed', file=sys.stderr)
        continue

    # Build serializer body.
    ser_lines = []
    for field_type, name, cli, kind in entries:
        if kind == 'bool':
            ser_lines.append(f"    if ({name} != null) m['{cli}'] = {name}.toString();")
        elif kind == 'string':
            ser_lines.append(f"    if ({name} != null) m['{cli}'] = {name}!;")
        elif kind == 'list':
            ser_lines.append(
                f"    if ({name} != null && {name}!.isNotEmpty) m['{cli}'] = {name}!.join(',');"
            )
        elif kind == 'enum':
            ser_lines.append(f"    if ({name} != null) m['{cli}'] = {name}!.toString();")

    ctor_params = ',\n'.join(f'    this.{n}' for _, n, _, _ in entries)
    fields = '\n'.join(f'  final {t} {n};' for t, n, _, _ in entries)
    ser_body = '\n'.join(ser_lines)

    out = f'''// Generated by tool/gen_options.py from `{filename}`.
// Do not edit by hand — regenerate when the underlying *Args class changes.

import '../args.dart';
import '../renderer_options.dart';

/// Named-parameter options for the {classname.removesuffix('RendererOptions')} target.
///
/// Pass to [QuicktypeDart.generate] via `options:`. Mirrors the flags
/// on the older [{classname.replace('RendererOptions', 'Args')}] class
/// (which is retained but deprecated — see migration notes in v0.3.0).
class {classname} extends RendererOptions {{
  const {classname}({{
{ctor_params},
  }});

{fields}

  @override
  Map<String, String> toRendererOptions() {{
    final m = <String, String>{{}};
{ser_body}
    return m;
  }}
}}
'''
    out_path = os.path.join(OPTS_DIR, filename)
    with open(out_path, 'w') as f:
        f.write(out)
    print(f'  wrote {out_path}: {len(entries)} fields')
    index_exports.append(filename)

# Emit a barrel.
barrel = os.path.join(OPTS_DIR, 'options.dart')
with open(barrel, 'w') as f:
    f.write('// Barrel — re-exports every language-specific RendererOptions class.\n\n')
    f.write("export '../renderer_options.dart';\n")
    for fn in index_exports:
        f.write(f"export '{fn}';\n")
print(f'  wrote {barrel}')
