/**
 * test.c
 * This file has been autogenerated using quicktype https://github.com/quicktype/quicktype - DO NOT EDIT
 * This file depends of https://github.com/DaveGamble/cJSON, https://github.com/joelguittet/c-list and https://github.com/joelguittet/c-hashtable
 * To parse json data from json string use the following: struct <type> * data = cJSON_Parse<type>(<string>);
 * To get json data from cJSON object use the following: struct <type> * data = cJSON_Get<type>Value(<cjson>);
 * To get cJSON object from json data use the following: cJSON * cjson = cJSON_Create<type>(<data>);
 * To print json string from json data use the following: char * string = cJSON_Print<type>(<data>);
 * To delete json data use the following: cJSON_Delete<type>(<data>);
 */

#ifndef __TEST_C__
#define __TEST_C__

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#include <string.h>
#include <cJSON.h>
#include <hashtable.h>
#include <list.h>

#ifndef cJSON_Bool
#define cJSON_Bool (cJSON_True | cJSON_False)
#endif
#ifndef cJSON_Map
#define cJSON_Map (1 << 16)
#endif
#ifndef cJSON_Enum
#define cJSON_Enum (1 << 17)
#endif

struct Test {
    char * asdf;
    char * asdf2;
};

struct Convert {
};

struct Test * cJSON_ParseTest(const char * s);
struct Test * cJSON_GetTestValue(const cJSON * j);
cJSON * cJSON_CreateTest(const struct Test * x);
char * cJSON_PrintTest(const struct Test * x);
void cJSON_DeleteTest(struct Test * x);

struct Convert * cJSON_ParseConvert(const char * s);
struct Convert * cJSON_GetConvertValue(const cJSON * j);
cJSON * cJSON_CreateConvert(const struct Convert * x);
char * cJSON_PrintConvert(const struct Convert * x);
void cJSON_DeleteConvert(struct Convert * x);

struct Test * cJSON_ParseTest(const char * s) {
    struct Test * x = NULL;
    if (NULL != s) {
        cJSON * j = cJSON_Parse(s);
        if (NULL != j) {
            x = cJSON_GetTestValue(j);
            cJSON_Delete(j);
        }
    }
    return x;
}

struct Test * cJSON_GetTestValue(const cJSON * j) {
    struct Test * x = NULL;
    if (NULL != j) {
        if (NULL != (x = cJSON_malloc(sizeof(struct Test)))) {
            memset(x, 0, sizeof(struct Test));
            if (cJSON_HasObjectItem(j, "asdf")) {
                x->asdf = strdup(cJSON_GetStringValue(cJSON_GetObjectItemCaseSensitive(j, "asdf")));
            }
            else {
                if (NULL != (x->asdf = cJSON_malloc(sizeof(char)))) {
                    x->asdf[0] = '\0';
                }
            }
            if (cJSON_HasObjectItem(j, "asdf2")) {
                x->asdf2 = strdup(cJSON_GetStringValue(cJSON_GetObjectItemCaseSensitive(j, "asdf2")));
            }
            else {
                if (NULL != (x->asdf2 = cJSON_malloc(sizeof(char)))) {
                    x->asdf2[0] = '\0';
                }
            }
        }
    }
    return x;
}

cJSON * cJSON_CreateTest(const struct Test * x) {
    cJSON * j = NULL;
    if (NULL != x) {
        if (NULL != (j = cJSON_CreateObject())) {
            if (NULL != x->asdf) {
                cJSON_AddStringToObject(j, "asdf", x->asdf);
            }
            else {
                cJSON_AddStringToObject(j, "asdf", "");
            }
            if (NULL != x->asdf2) {
                cJSON_AddStringToObject(j, "asdf2", x->asdf2);
            }
            else {
                cJSON_AddStringToObject(j, "asdf2", "");
            }
        }
    }
    return j;
}

char * cJSON_PrintTest(const struct Test * x) {
    char * s = NULL;
    if (NULL != x) {
        cJSON * j = cJSON_CreateTest(x);
        if (NULL != j) {
            s = cJSON_Print(j);
            cJSON_Delete(j);
        }
    }
    return s;
}

void cJSON_DeleteTest(struct Test * x) {
    if (NULL != x) {
        if (NULL != x->asdf) {
            cJSON_free(x->asdf);
        }
        if (NULL != x->asdf2) {
            cJSON_free(x->asdf2);
        }
        cJSON_free(x);
    }
}

struct Convert * cJSON_ParseConvert(const char * s) {
    struct Convert * x = NULL;
    if (NULL != s) {
        cJSON * j = cJSON_Parse(s);
        if (NULL != j) {
            x = cJSON_GetConvertValue(j);
            cJSON_Delete(j);
        }
    }
    return x;
}

struct Convert * cJSON_GetConvertValue(const cJSON * j) {
    struct Convert * x = NULL;
    if (NULL != j) {
        if (NULL != (x = cJSON_malloc(sizeof(struct Convert)))) {
            memset(x, 0, sizeof(struct Convert));
        }
    }
    return x;
}

cJSON * cJSON_CreateConvert(const struct Convert * x) {
    cJSON * j = NULL;
    if (NULL != x) {
        if (NULL != (j = cJSON_CreateObject())) {
        }
    }
    return j;
}

char * cJSON_PrintConvert(const struct Convert * x) {
    char * s = NULL;
    if (NULL != x) {
        cJSON * j = cJSON_CreateConvert(x);
        if (NULL != j) {
            s = cJSON_Print(j);
            cJSON_Delete(j);
        }
    }
    return s;
}

void cJSON_DeleteConvert(struct Convert * x) {
    if (NULL != x) {
        cJSON_free(x);
    }
}

#ifdef __cplusplus
}
#endif

#endif /* __TEST_C__ */
