<?php

// This is a autogenerated file:Test

class Test {
    private string $asdf; // json:asdf Required
    private string $asdf2; // json:asdf2 Required

    /**
     * @param string $asdf
     * @param string $asdf2
     */
    public function __construct(string $asdf, string $asdf2) {
        $this->asdf = $asdf;
        $this->asdf2 = $asdf2;
    }

    /**
     * @param string $value
     * @throws Exception
     * @return string
     */
    public static function fromAsdf(string $value): string {
        return $value; /*string*/
    }

    /**
     * @throws Exception
     * @return string
     */
    public function toAsdf(): string {
        if (Test::validateAsdf($this->asdf))  {
            return $this->asdf; /*string*/
        }
        throw new Exception('never get to this Test::asdf');
    }

    /**
     * @param string
     * @return bool
     * @throws Exception
     */
    public static function validateAsdf(string $value): bool {
        if (!is_string($value)) {
            throw new Exception("Attribute Error:Test::asdf");
        }
        return true;
    }

    /**
     * @throws Exception
     * @return string
     */
    public function getAsdf(): string {
        if (Test::validateAsdf($this->asdf))  {
            return $this->asdf;
        }
        throw new Exception('never get to getAsdf Test::asdf');
    }

    /**
     * @return string
     */
    public static function sampleAsdf(): string {
        return 'Test::asdf::31'; /*31:asdf*/
    }

    /**
     * @param string $value
     * @throws Exception
     * @return string
     */
    public static function fromAsdf2(string $value): string {
        return $value; /*string*/
    }

    /**
     * @throws Exception
     * @return string
     */
    public function toAsdf2(): string {
        if (Test::validateAsdf2($this->asdf2))  {
            return $this->asdf2; /*string*/
        }
        throw new Exception('never get to this Test::asdf2');
    }

    /**
     * @param string
     * @return bool
     * @throws Exception
     */
    public static function validateAsdf2(string $value): bool {
        if (!is_string($value)) {
            throw new Exception("Attribute Error:Test::asdf2");
        }
        return true;
    }

    /**
     * @throws Exception
     * @return string
     */
    public function getAsdf2(): string {
        if (Test::validateAsdf2($this->asdf2))  {
            return $this->asdf2;
        }
        throw new Exception('never get to getAsdf2 Test::asdf2');
    }

    /**
     * @return string
     */
    public static function sampleAsdf2(): string {
        return 'Test::asdf2::32'; /*32:asdf2*/
    }

    /**
     * @throws Exception
     * @return bool
     */
    public function validate(): bool {
        return Test::validateAsdf($this->asdf)
        || Test::validateAsdf2($this->asdf2);
    }

    /**
     * @return stdClass
     * @throws Exception
     */
    public function to(): stdClass  {
        $out = new stdClass();
        $out->{'asdf'} = $this->toAsdf();
        $out->{'asdf2'} = $this->toAsdf2();
        return $out;
    }

    /**
     * @param stdClass $obj
     * @return Test
     * @throws Exception
     */
    public static function from(stdClass $obj): Test {
        return new Test(
         Test::fromAsdf($obj->{'asdf'})
        ,Test::fromAsdf2($obj->{'asdf2'})
        );
    }

    /**
     * @return Test
     */
    public static function sample(): Test {
        return new Test(
         Test::sampleAsdf()
        ,Test::sampleAsdf2()
        );
    }
}

// This is a autogenerated file:Convert

class Convert {

    /**
     */
    public function __construct() {
    }

    /**
     * @throws Exception
     * @return bool
     */
    public function validate(): bool {
    }

    /**
     * @return stdClass
     * @throws Exception
     */
    public function to(): stdClass  {
        $out = new stdClass();
        return $out;
    }

    /**
     * @param stdClass $obj
     * @return Convert
     * @throws Exception
     */
    public static function from(stdClass $obj): Convert {
        return new Convert(
        );
    }

    /**
     * @return Convert
     */
    public static function sample(): Convert {
        return new Convert(
        );
    }
}
