# This file was autogenerated using quicktype https://github.com/quicktype/quicktype
#
# Add Jason to your mix.exs
#
# Decode a JSON string: Test.from_json(data)
# Encode into a JSON string: Test.to_json(struct)
#
# Decode a JSON string: Convert.from_json(data)
# Encode into a JSON string: Convert.to_json(struct)

defmodule Test do
  @enforce_keys [:asdf, :asdf2]
  defstruct [:asdf, :asdf2]

  @type t :: %__MODULE__{
          asdf: String.t(),
          asdf2: String.t()
        }

  def from_map(m) do
    %Test{
      asdf: m["asdf"],
      asdf2: m["asdf2"],
    }
  end

  def from_json(json) do
    json
          |> Jason.decode!()
          |> from_map()
  end

  def to_map(struct) do
    %{
      "asdf" => struct.asdf,
      "asdf2" => struct.asdf2,
    }
  end

  def to_json(struct) do
    struct
          |> to_map()
          |> Jason.encode!()
  end
end

defmodule Convert do
  defstruct []

  @type t :: %__MODULE__{
        }

  def from_map(_m) do
    %Convert{
    }
  end

  def from_json(json) do
    json
          |> Jason.decode!()
          |> from_map()
  end

  def to_map(_struct) do
    %{
    }
  end

  def to_json(struct) do
    struct
          |> to_map()
          |> Jason.encode!()
  end
end
